log_filepath: "logs/vit_train.log"

cifar_dataset:
  train_label_type: "coarse"
  image_size: 32

optimizer:
  name: "adam"
  learning_rate: 0.0001

lr_scheduler:
  type: "linear"
  lr: 0.0003

training:
  num_epochs: 3
  validation_epoch_interval: 1
  batch_size: 2