log_dir: "/home/iony/DTU/f24/thesis/vit_pytorch/logs"
log_filename: "vit_train.log"

cifar_dataset:
  label_type: "coarse"
  train_split: "train[:100]"
  validation_split: "test[:10]"
  test_split: "test[:100]"

  image_size: 32

optimizer:
  name: "adam"
  learning_rate: 0.0001

lr_scheduler:
  type: "linear"
  lr: 0.0003

training:
  num_epochs: 3
  validation_epoch_interval: 1
  batch_size: 2
  results_dir: "/home/iony/DTU/f24/thesis/vit_pytorch/results"